name: ci: export Next to deploy-static for Hostinger

on:
  push:
    branches:
      - main

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Write commit hash
        run: echo "${{ github.sha }}" > public/commit.txt

      - name: Build + export Next
        run: |
          npm run build
          npx next export -o out

      - name: Push export to deploy-static branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git fetch origin
          git checkout -B deploy-static
          rm -rf .next node_modules
          cp -r out/* .
          rm -rf out
          git add -A
          git commit -m "Deploy ${{ github.sha }}"
          git push -f origin deploy-static